Task#5: Packer
Otus-DevOps-2019-08/whoami-io_infra pull request #5
Opened 2019-09-28 23:33 UTC by whoami-io

# Выполнено ДЗ №5

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - приготовлен 'fry' образ 'reddit-base'
 - приготовлен 'bake' образ 'reddit-full'
 - при сборке образа используется файл с параметрами
 - инстанс с запущенным приложением при помощи systemd unit
 - образ 'reddit-full' собирается на основе 'reddit-base'
- скрипт для запуска в GCP инстанса VM с кастмным образом  'reddit-full'

#### Домашнее задание: Сборка образа при помощи Packer

1. Создан образ VM  `reddit-base`(без параметров)
./packer
```
packer build ubuntu16.json
```
2. Создан образ VM `reddit-base` (с параметрами)

./packer 
```
packer build -var-file=variables.json.example  ubuntu16.json
```

3. Запускаем инстанс из созданного образа и на нем сразу
же имеем запущенное приложение:

Cобираем образ:

./packer 
```
packer build -var-file=variables.json.example  immutable.json
```
Чтобы собрать образ на основе 'reddit-base', указываем: 

./immutable.json
```
"source_image_family": "reddit-base",
```

Чтобы приложение сразу запустилось, добавим автозапуск команды `puma -d` при помощи Systemd: 

./files/reddit-start.service

```
[Unit]
Description=StartRedditApp // что делает сервис, просто полезное описание

[Service]
ExecStart=/usr/local/bin/puma --dir /home/appuser/reddit // эквивалент puma -d, требует абсолютные пути

[Install]
WantedBy=multi-user.target // разрешить запуск из консоли
```

Добавим этот шаг в immutable.json:

./packer/immutable.json
```  ...
    "provisioners": [
       {
            "type": "file",
            "source": "files/reddit-start.service",
            "destination": "/tmp/reddit-start.service" // куда положить файл
       },
              {
            "type": "shell",
            "script": "scripts/deploy.sh", 
	    /*
	    // sudo mv /tmp/reddit-start.service /etc/systemd/system/ // перекопировать файл в дефолтную директорию
	    // и помечаем файл как только на чтение/запись, но не выполнение
            // sudo chmod 664 /etc/systemd/system/reddit-start.service
	    // sudo systemctl enable reddit-start 
	    //
	    */
            "execute_command": "sudo {{.Path}}"
       }
       ...
```

Cобираем образ:

./packer 
```
packer build -var-file=variables.json.example  immutable.json
```

4. Запустить одной командой инстанс в GCP с запущенным приложением:
```
./config-scripts/create-redditvm.sh
```

## Как запустить проект:
 - Запустить команду `./config-scripts/create-redditvm.sh`

## Как проверить работоспособность:
 - Запустить команду `./config-scripts/create-redditvm.sh` и перейти по ссылке http://35.208.161.9:9292

## PR checklist
 - [x] Добавьте "Labels" packer-base и Packer к вашему Pull Request

2019-09-29 13:49 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарии к файлам. Вам нужно поправить все что связано с юнит файлом для пумы. В таком варианте не заведется. Возвращаю на доработку.

2019-09-29 13:49 UTC, mrgreyves commented on packer/files/reddit-start.service
> +ExecStart=/usr/local/bin/puma --dir /home/appuser/reddit
Стоит добавить пользователя и тип сервиса, как минимум. Более детально про типы сервисов вы можете посмотреть в документации для systemd =)

2019-09-29 13:49 UTC, mrgreyves commented on packer/scripts/deploy.sh
> +sudo chmod 664 /etc/systemd/system/reddit-start.service
Эммм, а daemon-reload где то потерялся?0_о

2019-09-29 21:55 UTC, whoami-io commented on packer/scripts/deploy.sh
> +sudo chmod 664 /etc/systemd/system/reddit-start.service
почитала, добавила

2019-09-29 21:55 UTC, whoami-io commented on packer/files/reddit-start.service
> +ExecStart=/usr/local/bin/puma --dir /home/appuser/reddit
почитала, добавила

2019-10-02 08:21 UTC, mrgreyves approved these changes
Здравствуйте!) Перепроверил ваше дз. Хорошо что делаете проверки в скриптах. ДЗ принимаю!=)

2019-10-02 08:38 UTC, merged